### PR TITLE
Autogen EGL and GLES

### PR DESCRIPTION
**Pull request by thejudge156**
OpenGL stubs and auto function passthrough is out of scope for this PR

Note: For bindgen you need LLVM and the env variable LIBCLANG_PATH="C:\Program Files\LLVM\bin\libclang.dll"

### CODE REVIEW

**Review by CADIndie — APPROVED** [review]

**Comment by CADIndie** [comment]
@artdeell Please review the changes once you have time.

**Comment by Mathias-Boulay** [comment]
The GLES header file seems awfully light. 
Are we sure we are accounting for GLES 3.X capabilities ?
image

**Comment by Mathias-Boulay** [comment]
Also, it will be vital to maintain documentation regarding build instructions somewhere, like a readme.
Therefore the note that @thejudge156 made should be consigned elsewhere than just the text of the PR

**Comment by CADIndie** [comment]
> Also, it will be vital to maintain documentation regarding build instructions somewhere, like a readme. Therefore the note that @thejudge156 made should be consigned elsewhere than just the text of the PR

I've opened #2 as a draft which can be updated as we figure out the build process some more.

**Comment by CADIndie** [comment]
@thejudge156 Please ensure you utilize the proper naming scheme when creating branches in the future.

**Comment by thejudge156** [comment]
> The GLES header file seems awfully light. Are we sure we are accounting for GLES 3.X capabilities ? image

Good catch.

**Comment by thejudge156** [comment]
Fixed

**Comment by thejudge156** [comment]
We probably can wait on that part as we assess further.

**Comment by Mathias-Boulay** [comment]
> We probably can wait on that part until we assess requirements further.
Fair enough.
Remember to update the rust bindings to take into account the new headers, gles 3.X functions are missing

**Comment by Mathias-Boulay** [comment]
btw, very nice `.unwrap()` calls inside the `build.rs`.

I'll let it slide, it is not part of the final binary anyway.

As for future commits, using the conventional commits name scheme might prove useful in increasing readability to know which commit does what.

**Review by Mathias-Boulay — APPROVED** [review]

**Pull request merged**
